# Homework 1

Please submit the solution to gradescope by 11:59 PM, Sept 12, Thursday.

**Name**: Robert Nachnani

**PID**: 730573785


In [1]:
import string

## Problem 1 (25 points). 

**1.1** (20 points) Load a text file `file.txt`, clean its content by 


 - removing all punctuation
 - removing extra white spaces
 - transforming the text to lowercase.

Print the cleaned text. 

**1.2** (5 points) Count and print the number of vowels present in the cleaned text

   Example input: `s = "hello world"`

   Example output: `a = 0, e = 1, i = 0, o = 2, u = 0`

In [2]:
#Question 1.1

def clean_text(file_name):
    with open(file_name, "r") as file:
        text = file.read()

    text = text.translate(str.maketrans("", "", string.punctuation))
    text = " ".join(text.split())
    text = text.lower()

    return text

file_path = "file.txt"
cleaned_text = clean_text(file_path)
print(cleaned_text)

#Used a method I have learned in the past to complete this

development of basic skill set for data analysis in python from obtaining data to data carpentry exploration modeling and communication lectures cover topics such as python programming data cleaning and visualization predictive modeling and elements of machine learning the course will develop fluency in the python language and the standard scientific libraries such as numpy pandas matplotlib and scikitlearn programming analyses in more advanced areas of data science plan to come to every class with your computer and ready to work with others using resources around you is a key component of successful data analysis this includes the internet and people students may not receive credit for both stor 320 and stor 520


In [3]:
#Questiion 1.2 / I used a method I previously learned if that's okay

def find_vowels(text):
    vowels = "aeiou"
    vowel_count = {vowel: 0 for vowel in vowels}
    
    for char in text:
        if char in vowel_count:
            vowel_count[char] += 1
    
    return vowel_count

find_vowels(cleaned_text)

{'a': 59, 'e': 58, 'i': 44, 'o': 46, 'u': 19}

## Problem 2. (25 point). 

You are organizing information about several data science courses. Given the nested list of tuples `courses = [(101, 'Intro to Data Science'), (201, 'Machine Learning'), (103, 'Data Visualization'), (102, 'Python Programming')]`, perform the following tasks:

**2.1** (5 points) Convert the list of tuples into a dictionary where the course number is the key and the course name is the value.

**2.2** (5 points) Add a new course `(202, 'Deep Learning')` to the dictionary.

**2.3** (5 points) Sort the dictionary based on the course number. 

**2.4** (5 points) Update the dictionary based on the following instruction: `Intro to Data Science` course is combined with `Python Programming` course, called `Intro to Data Science with Python` and the course number is still `101`. Delete the course `Python Programming`.

**2.5** (5 points) Extract the course numbers and course names from the updated dictionary and store them in separate lists, e.g., `[101, 102, 103, 201, 202]`, `['Intro to Data Science with Python', 'Data Visualization',...]`




In [4]:
#Question 2.1
courses = {101 : "Intro to Data Science", 201 : "Machine Learning", 103 : "Data Visualization", 102 : "Python Programming"}

#Testing
type(courses), courses[101]

(dict, 'Intro to Data Science')

In [5]:
#Question 2.2
courses[202] = "Deep Learning"

courses

{101: 'Intro to Data Science',
 201: 'Machine Learning',
 103: 'Data Visualization',
 102: 'Python Programming',
 202: 'Deep Learning'}

In [6]:
#Question 2.3
sorted_courses = dict(sorted(courses.items()))

sorted_courses

{101: 'Intro to Data Science',
 102: 'Python Programming',
 103: 'Data Visualization',
 201: 'Machine Learning',
 202: 'Deep Learning'}

In [7]:
#Question 2.4
courses[101] = "Intro to Data Science with Python"
del courses[102]

courses

{101: 'Intro to Data Science with Python',
 201: 'Machine Learning',
 103: 'Data Visualization',
 202: 'Deep Learning'}

In [8]:
#Question 2.5
course_nums = list(courses.keys())
course_names = list(courses.values())

course_nums , course_names

([101, 201, 103, 202],
 ['Intro to Data Science with Python',
  'Machine Learning',
  'Data Visualization',
  'Deep Learning'])

## Problem 3 (25 points). 

You have two lists of student IDs enrolled in two different data science courses: `course1_ids = [101, 102, 102, 103, 104]` and `course2_ids = [103, 104, 104, 105, 106]`. Perform the following tasks:

**3.1** (5 points) Convert the lists to sets to remove duplicate IDs.

**3.2** (10 points) Find the union and intersection of the two sets to determine which students are in either or both courses.

**3.3** (5 points) Convert the union and intersection sets to sorted lists.

**3.4** (5 points) Create a dictionary where the keys are the student IDs from the union list and the values are True if the student is in both courses, otherwise False.

In [9]:
#Question 3.1
course1_ids = [101, 102, 102, 103, 104]
course2_ids = [103, 104, 104, 105, 106]

course1_set = set(course1_ids)
course2_set = set(course2_ids)


course1_set , course2_set

({101, 102, 103, 104}, {103, 104, 105, 106})

In [10]:
#Question 3.2 
union_set = course1_set.union(course2_set)
intersection_set = course1_set.intersection(course2_set)

union_set , intersection_set

({101, 102, 103, 104, 105, 106}, {103, 104})

In [11]:
#Question 3.3
union_list = sorted(list(union_set))
intersection_list = sorted(list(intersection_set))

union_list , intersection_list

([101, 102, 103, 104, 105, 106], [103, 104])

In [12]:
#Question 3.4
student_dict = {id: (id in intersection_list) for id in union_list}
student_dict

#Used method I have learned previously

{101: False, 102: False, 103: True, 104: True, 105: False, 106: False}

# Problem 4 (25 points)

**4.1** (5 points) Install a package `sympy`. The `sympy` library is a Python library for symbolic mathematics. You do not have to install this library again if it is already installed. 

**4.2** (10 points) `isprime` function in `sympy` checks if a number is a prime number. For example, `isprime(7)` returns `True`. Based on this function, define a function to find the closest prime number of an integer. For example, if the input is 8, the function should return 7, as it is the closest prime number.



**4.3** (5 points) Treat your PID number at UNC as an integer, and print its closest prime number.

**4.4** (5 points) Given this sequence `[456,983,482,963,749,12,97]`, create a new list where each element is replaced by the closest prime number to that element, using the function defined in **4.2**.



In [13]:
from sympy import isprime

In [14]:
#Question 4.1
!pip install sympy

In [18]:
#Question 4.2
def closest_prime(n):
    lower = n - 1
    higher = n + 1
    
    if isprime(n):
        return n


    while True:
        if isprime(lower):
            return lower
        if isprime(higher):
            return higher

        lower -= 1
        higher += 1

closest_prime(14) , closest_prime(7) , closest_prime(234203580183427)

(13, 7, 234203580183431)

In [19]:
#Question 4.3
closest_prime(730573785)

730573801

In [20]:
#Question 4.4
number_list = [456,983,482,963,749,12,97]
new_number_list = [closest_prime(num) for num in number_list]


new_number_list

[457, 983, 479, 967, 751, 11, 97]